# SonarCloud Automatic Analysis Configuration
sonar.sources=src,server,shared,app
sonar.tests=tests
sonar.exclusions=coverage/**,**/coverage/**,dist/**,node_modules/**,**/*.html,**/*.css,**/*.json,public/**
sonar.test.inclusions=tests/**/*.ts
sonar.javascript.lcov.reportPaths=coverage/lcov.info
